# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a proprietary
# license that can be found in the LICENSE file.

---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: tap
        versions:
          - 15.0.0
          - 15.0.1
          - 15.0.2
          - 15.0.3
          - 15.0.4
